import type {Metadata} from "next";
import {Sora} from "next/font/google";
import "./globals.css";

import GameProvider from "@/context/GameContext/GameProvider";

const soraFont = Sora({
	display: "swap",
	style: ["normal"],
	subsets: ["latin", "latin-ext"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
	title: "Typing Speed Test",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en-US">
			<GameProvider>
				<body className={`${soraFont.className}`}>{children}</body>
			</GameProvider>
		</html>
	);
}
